### ISSUE TITLE
Fontsize inconsistency in fullscreen mode

### ISSUE THREAD

**Issue by vbonvin** [AlbinJS/IPTClock#30]
When going fullscreen on my system (fresh python3 / matplotlib / tkinter backend) the fontsize is by default way too big:

![fullscreen_defaultfont](https://cloud.githubusercontent.com/assets/12261805/24134077/1b847e5c-0e02-11e7-9808-476927c6b163.png)

When trying to reduce the size with ctrl + - it makes some of the lines (like the participants' names or the start / stop buttons on the right ) really tiny where the countdown is still quite large and the clock itself stays quite small

![fullscreen_minusonft](https://cloud.githubusercontent.com/assets/12261805/24134117/5114321a-0e02-11e7-8ce0-0e00e21c5224.png)

A possible fix would be to hardcode the fontsize in config.py so that each user can adapt it to his/her system ?

**Comment by AlbinJS** [comment]
The way of hard coding is rocky and user unfriendly...
I agree that the scaling results in some ugly configurations. I don't think this should be hard coded but maybe scaled differently. Presently the scaling is done by linearly just adding or subtracting a 1 to the present font size. I could try and change it so that the countdown font size is modified with a higher number. I'll look into it.

**Comment by vbonvin** [comment]
>The way of hard coding is rocky and user unfriendly...

Keep in mind that hard coding in the core files can be bad, but it is perfectly OK to have it in a configuration file. Especially if the final display is backend dependent (I don't know if it is the case here) 

Now if you manage to solve it by changing the scaling that's perfectly fine.

**Comment by AlbinJS** [comment]
Since the latest commit, the possibility to manually edit each font size is added. This is done by using the new configuration windows under the "Edit" menu. Although the automatic scaling isn't without fault it has been improved somewhat. I'm closing this issue. Feel free to open a new or ask me to reopen this issue if you are of a different mind.
