### ISSUE TITLE
Summarize multiple running clocks on a single display

### ISSUE THREAD

**Issue by vbonvin** [AlbinJS/IPTClock#34]
That is certainly a complicated feature to code and you certainly won't have time to do it before IPT2017 but it might be a really cool improvement for the future (I'd be happy to help with the code):

The idea is to have a webpage somewhere to which various clocks can connect, and the webpage displays a lighter version of the current stage + remaining/elapsed time for all the clocks. This would serve as some kind of summary of the ongoing fights in the whole tournament.

**Comment by AlbinJS** [comment]
I agree that it would be cool, but I also think it would be more of a gimmick and not particularly useful. Such a project would probably have the best changes for success if the clock where rewritten so that all the clocks are being runned on a web server instead of locally on a computer. Of course you could also just let each clock update some variable and let the web server do the rest. Anyhow, I don't feel to enthusiastic doing that work.

**Comment by AlbinJS** [comment]
Although an interesting idea, I don't think it belongs in the issues for this program since I think that it should be a seperate project. I'm closing this issue.
