### ISSUE TITLE
Add a clock marker for 30 seconds/10% left?

### ISSUE THREAD

**Issue by joel-magnusson** [AlbinJS/IPTClock#7]
This could be done by having another wedge of another color for the final part of the clock. Other "low health"-effects could be added simultaneously (such as a beeping sound).

**Comment by AlbinJS** [comment]
Actually, I strongly believe that a sound will be against the nature of the IPT tournament and would be disturbing. "low health" -effects in the form of color change etc. could be implemented. Though I believe that that causes more of a contest for the public mode, rather than an academic reasoning atmosphere.

**Comment by AlbinJS** [comment]
Has now been implemented. I'm closing the issue.
